In [ ]:
# Import required libraries
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

print("Libraries imported successfully")
print(f"NumPy version: {np.__version__}")


Libraries imported successfully
NumPy version: 2.2.3
Pandas version: 2.2.3
Matplotlib version: 3.10.1
Seaborn imported for statistical visualization


# Exercise 1: Matrices Fundamentals and Linear Transformations - Theory and Implementation


---

## Part 1: Matrix Basics

### 1.1: Creating Matrices

- Create a $2 \times 3$ matrix and a $3 \times 2$ matrix using Python lists and numpy.

In [ ]:
# From scratch
A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8], [9, 10], [11, 12]]
print("A (Lists):\n", A)
print("B (Lists):\n", B)

# Using NumPy
A_np = np.array([[1, 2, 3], [4, 5, 6]])
B_np = np.array([[7, 8], [9, 10], [11, 12]])
print("A (NumPy):\n", A_np)
print("B (NumPy):\n", B_np)

A (Lists):
 [[1, 2, 3], [4, 5, 6]]
B (Lists):
 [[7, 8], [9, 10], [11, 12]]
A (NumPy):
 [[1 2 3]
 [4 5 6]]
B (NumPy):
 [[ 7  8]
 [ 9 10]
 [11 12]]


## Part 2: Matrix Operations

### 2.1: Matrix Addition and Subtraction

**Definition:** 
Given two matrices $A, B \in \mathbb{R}^{m \times n}$, their sum $C = A + B$ is defined as:
$$
C_{ij} = A_{ij} + B_{ij} \quad \forall\, 1 \leq i \leq m,\ 1 \leq j \leq n
$$

- Implement matrix addition from scratch (using lists) and NumPy.
- What happens if the shapes do not match? Try it and explain.

In [ ]:
# From scratch
def matrix_add(A, B):
    # TODO: YOUR IMPLEMENTATION HERE
    pass


# Test with A and another 2x3 matrix
A = [[5, 2, 4], [1, 8, 6]]
B = [[10, 20, 30], [40, 50, 60]]

print("A + B (from scratch):", matrix_add(A, B))

# NumPy
print("A + B (NumPy):", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Use the + operator

A + B (from scratch): [[15, 22, 34], [41, 58, 66]]
A + B (NumPy): [[15 22 34]
 [41 58 66]]


### 2.2: Matrix Scalars Multiplication
**Definition:** 
Given a scalar $\lambda \in \mathbb{R}$ and a matrix $A \in \mathbb{R}^{m \times n}$, the scalar multiplication $\lambda A$ is defined as:
$$
(\lambda A)_{ij} = \lambda \cdot A_{ij} \quad \forall\, 1 \leq i \leq m,\ 1 \leq j \leq n
$$

- Multiply a matrix by a scalar using lists, NumPy.


In [ ]:
# From scratch
def matrix_scalar_mul(A, d):
    # TODO: YOUR IMPLEMENTATION HERE
    pass


# Test with A and a scalar
d = 3
A = [[10, 20, 30], [40, 50, 60]]
print("A + B (from scratch):", matrix_scalar_mul(A, 3))

# NumPy
print("A + B (NumPy):", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Use the * operator

A + B (from scratch): [[30, 60, 90], [120, 150, 180]]
A + B (NumPy): [[ 30  60  90]
 [120 150 180]]


### 2.3: Matrix Transpose

**Definition:**
The **transpose** of a matrix $A \in \mathbb{R}^{m \times n}$ is $A^T \in \mathbb{R}^{n \times m}$, defined by:
$$
(A^T)_{ij} = A_{ji}
$$

- Write a function to transpose a matrix (List of Lists) and NumPy.

In [ ]:
# From scratch
def transpose(A):
    # TODO: YOUR IMPLEMENTATION HERE
    pass

A = [[4, 1], [6, 2], [9, 6]]
A_np = np.array(A)
print("Transpose of A (from scratch):", transpose(A))
print("Transpose of A (NumPy):\n", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Use the .T attribute

Transpose of A (from scratch): [[4, 6, 9], [1, 2, 6]]
Transpose of A (NumPy):
 [[4 6 9]
 [1 2 6]]


### 2.4: Matrix Multiplication

**Definition:** 
Given $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$, their product $C = AB \in \mathbb{R}^{m \times p}$ is:
$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

- Implement matrix multiplication from scratch and numpy
- Try multiplying A and B, and B and A. What do you notice about the shapes?

In [ ]:
def matmul(A, B):
    # TODO: YOUR IMPLEMENTATION HERE
    pass

A = [[4, 1], [6, 2], [9, 6]]
B = [[10, 20, 30], [40, 50, 60]]
A_np, B_np = np.array(A), np.array(B)
print("A x B (from scratch):", matmul(A, B))
print("A x B (NumPy):\n", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Use np.dot

A x B (from scratch): [[80, 130, 180], [140, 220, 300], [330, 480, 630]]
A x B (NumPy):
 [[ 80 130 180]
 [140 220 300]
 [330 480 630]]


- Matrix multiplication could also be done in numpy in other ways:


In [ ]:
# 1. Using np.dot()
print("np.dot(A, B):\n", np.dot(A, B))

# 2. Using the @ operator (Python 3.5+)
print("A @ B:\n", A @ B)

# 3. Using np.matmul()
print("np.matmul(A, B):\n", np.matmul(A, B))

# 4. Using A.dot(B) method
print("A.dot(B):\n", A.dot(B))

### 2.5: Transpose of a Matrix Product

**Definition:** 
This property states that, for matrices $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$,
$$
(AB)^T = B^T A^T
$$

- Fill in the code below to verify this property using NumPy.

In [ ]:
A = np.random.randint(0, 10, (2, 3))
B = np.random.randint(0, 10, (3, 2))

print("A:\n", A)
print("B:\n", B)

left_Term = None  # TODO: IMPLEMENTATION HERE
right_Term = None # TODO: IMPLEMENTATION HERE

print("Transpose of product property holds?")
print("(AB)^T", left_Term)
print("B^T A^T", right_Term)

A:
 [[3 5 1]
 [9 1 9]]
B:
 [[3 7]
 [6 8]
 [7 4]]
Transpose of product property holds?
(AB)^T:  [[ 46  96]
 [ 65 107]]
B^T A^T:  [[ 46  96]
 [ 65 107]]


## Part 3: Vector Spaces, Linear Combinations, and Linear Transformations

### 3.1: Linear Combination

**Definition:** 
Given vectors $v_1, v_2, ..., v_k \in V$ and scalars $a_1, ..., a_k \in \mathbb{R}$, a **linear combination** is:
$$
a_1 v_1 + a_2 v_2 + \cdots + a_k v_k
$$

- Given $v_1 = [1, 2]$, $v_2 = [3, 4]$, compute $2v_1 - v_2$ using lists and NumPy.

In [ ]:
# From scratch (lists)
def linear_combination(v1, v2):
    # TODO: Fill in to compute 2*v1 - v2
    pass

v1 = [1, 2]
v2 = [3, 4]
print("2v1 - v2 (from scratch):", linear_combination(v1, v2))

# Using NumPy
v1_np = np.array(v1)
v2_np = np.array(v2)
print("2v1 - v2 (NumPy):", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Use * and - operators

2v1 - v2 (from scratch): [-1, 0]
2v1 - v2 (NumPy): [-1  0]


### 3.2: Linear Transformations
 
**Definition:** 
A **linear transformation** $T: \mathbb{R}^n \to \mathbb{R}^m$ is a function such that for all $u, v \in \mathbb{R}^n$ and $a, b \in \mathbb{R}$:
$$
T(a u + b v) = a T(u) + b T(v)
$$
Every linear transformation can be represented by a matrix $A$ such that $T(x) = Ax$.

- **Task:** Implement a function that applies a matrix $A$ to a vector $v$ (i.e., computes $Av$) from scratch and NumPy.

In [ ]:
# From scratch
def apply_matrix(A, v):
    # TODO: Fill in to compute matrix-vector multiplication
    pass

# Example: 90 degree rotation in 2D
R = [[0, -1],
     [1, 0]]
v = [1, 0]
print("Rotated vector (from scratch):", apply_matrix(R, v))

# Using NumPy
import numpy as np
R_np = np.array(R)
v_np = np.array(v)
print("Rotated vector (NumPy):", ) # TODO: YOUR IMPLEMENTATION HERE. Hint: Just normal matmul

Rotated vector (from scratch): [-1, 1]
Rotated vector (NumPy): [-1  1]


**Definition:**  
Any linear transformation $T: \mathbb{R}^n \to \mathbb{R}^n$ can be represented by a matrix $A$ whose columns are the images of the standard basis vectors under $T$.  
That is, if $e_1, e_2, ..., e_n$ are the standard basis vectors, then:
$$
A = \begin{bmatrix} T(e_1) & T(e_2) & \cdots & T(e_n) \end{bmatrix}
$$
Applying $A$ to any vector $v$ gives $T(v)$.

- **Task:**  
Suppose we want a transformation $T$ such that for any vector $v = \begin{bmatrix} a \\ b \\ c \end{bmatrix}$,  
$T\left(\begin{bmatrix}a\\b\\c\end{bmatrix}\right) = \begin{bmatrix}a + b\\a + c\\b + c\end{bmatrix}$.

Fill in the code to construct the transformation matrix $A$ and verify that it works for any 3-dimensional vector $v$.

In [ ]:
# TODO: Fill in the transformation matrix A so that A @ [a, b, c] = [a + b, a + c, b + c]
A = None  # Should be a 3x3 matrix

# TODO: Fill in the basis vectors e1, e2, e3

print("e1 After Transformation", )  # TODO: Test the transformation with basis vector e1
print("e2 After Transformation", )  # TODO: Test the transformation with basis vector e2
print("e3 After Transformation", )  # TODO: Test the transformation with basis vector e3

# Test the transformation on another vector, e.g., v = [2, 3, 4]
v = np.array([2, 3, 4])
print("Vector v After Transformation", ) # TODO: Test the transformation with some vector v

A @ e1 = [1 1 0]
A @ e2 = [1 0 1]
A @ e3 = [0 1 1]
A @ v = [5 6 7]


### 3.3: Inner Product

**Definition:**  
The **inner product** (also called the dot product) of two vectors $u, v \in \mathbb{R}^n$ is defined as:
$$
\langle u, v \rangle = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n = \sum_{i=1}^n u_i v_i
$$

- **Task:** Implement the inner product of two vectors from scratch, and then see how it is done using NumPy.

In [ ]:
# From scratch
def inner_product(u, v):
    # TODO: Fill in to compute the inner product of u and v
    pass

u = [1, 2, 3]
v = [4, 5, 6]
print("Inner product (from scratch):", inner_product(u, v))

# Using NumPy
u_np = np.array(u)
v_np = np.array(v)
print("Inner product (NumPy):", ) # TODO: Fill in your code here. Hint: use np.dot

Inner product (from scratch): 32
Inner product (NumPy): 32


## Part 4: Some Important Square Matrices

### 4.1: Diagonal Matrices

**Definition:**  
A **diagonal matrix** is a square matrix where all off-diagonal elements are zero. That is, $D_{ij} = 0$ for all $i \neq j$.

**Power Property:**  
For a diagonal matrix $D$, raising it to the $k$-th power is the same as raising each diagonal entry to the $k$-th power:
$$
D^k = \text{diag}(d_1^k, d_2^k, \ldots, d_n^k)
$$

- **Task:** Fill in the code to verify the power property for diagonal matrices.

In [ ]:
D = np.diag([2, 3, 4])
k = 3

# TODO: Fill in to verify the power property for diagonal matrices
left = None  # D raised to the power k
right = None # diag([2**k, 3**k, 4**k])
print("Power property holds?", np.allclose(left, right)) # allclose checks if two matrices are equal

Power property holds? True


### 4.2: Orthogonal Matrices

**Definition:**  
A square matrix $Q$ is **orthogonal** if $Q^T Q = Q Q^T = I$, where $I$ is the identity matrix. This means the columns (and rows) of $Q$ are orthonormal vectors.

- **Task:** Fill in the code to verify whether a given matrix is orthogonal.

In [ ]:
Q = np.array([[0, 1], [1, 0]])  # Example: permutation matrix

# TODO: Fill in to check if Q is orthogonal
is_orthogonal = None  #Hint: Use np.allclose, np.eye
print("Is Q orthogonal?", is_orthogonal)

Is Q orthogonal? True


### 4.3: Symmetric Matrices

**Definition:**  
A matrix $A$ is **symmetric** if $A = A^T$.
- **Task:** Fill in the code to verify whether a given matrix is symmetric.

In [ ]:
A = np.array([[1, 2, 3], [2, 5, 6], [3, 6, 9]])

# TODO: Fill in to check if A is symmetric
is_symmetric = None  # Use np.allclose, which checks if 2 matrices are equal
print("Is A symmetric?", is_symmetric)

Is A symmetric? True
